#配置数据源
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/migrate?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver